### ISSUE TITLE
keyerror on get_completed_tasks

### ISSUE THREAD

**Issue by ryqiem** [Garee/pytodoist#24] opened 2018-04-20 16:51 UTC
Last week my script started throwing errors when getting tasks in a project, but only for some projects. I created new projects, moved my tasks there, and all was fine for a while. However, now it's resurfacing with the new projects.

```
Traceback (most recent call last):
  File "script.py", line 64, in <module>
    copy_due("Tickler", "Solitary-actionable")
  File "script.py", line 36, in copy_due
    due_tasks = user.get_project(inp).get_uncompleted_tasks()
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 1026, in get_uncompleted_tasks
    completed_tasks = self.get_completed_tasks()
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 1058, in get_completed_tasks
    project = self.owner.projects[task_json['project_id']]
KeyError: 1490683247
```

Any ideas?

**Comment by Garee** [comment] 2018-04-20 17:34
Sometimes there are bugs in Todoist that are surfaced through their API (which PyTodoist uses.) They often go away after a few days when they are fixed on the Todoist end.

This may go away by itself but I'll have a look to see if there is an issue I can fix.

**Comment by ryqiem** [comment] 2018-05-05 13:15
It seems the error has escalated further:

```
Traceback (most recent call last):
  File "/home/martin/scripts/tickler-todoist/script.py", line 13, in <module>
    user = todoist.login('ryqiem@gmail.com', 'supersecretpassword')
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 45, in login
    user = _login(API.login, email, password)
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 102, in _login
    return User(user_json)
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 310, in __init__
    self.sync()
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 350, in sync
    self._sync_tasks(response_json['items'])
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 371, in _sync_tasks
    project = self.projects[project_id]
KeyError: 182086891
```

**Comment by Garee** [comment] 2018-05-05 13:29
I am struggling to reproduce this. Does the error happen every time you run the script or is it inconsistently failing?

**Comment by Garee** [comment] 2018-05-07 09:28
Thanks for the additional information @pete-adriano-debiase 

PyTodoist hasn't changed recently which leads me to believe that it is indeed a bug in the Todoist API. It looks like they are returning invalid project IDs in the response.

I'll have another go at reproducing this.

**Comment by pete-adriano-debiase** [comment] 2018-06-04 11:05
Hi @Garee,

I spent a bit more time digging into this tonight. Per your suspicion, Todoist is indeed returning invalid project IDs for what appears to be a very particular subset of tasks.

Specifically, at least in my Todoist account, tasks completed prior to 2018-04-09 in projects created prior to 2018-04-09 seem to have nine-digit project IDs starting with a `1` (such as `137_028_573`). Tasks completed on or after 2018-04-09 in projects created prior to 2018-04-09 seem to have nine-digit project IDs starting with a `9` (such as `942_334_941`). The difference between the 9-prefixed project IDs and the 1-prefixed project IDs is always exactly `805_306_368`.

Furthermore, it appears that projects created on or after approximately 2018-04-09 have ten-digit project IDs starting with a `2` (such as `2_168_462_001`).

Among tasks with 1-prefixed project IDs, 9-prefixed project IDs, and 2-prefixed project IDs, the `get_completed_tasks()` function only returns the `KeyError` exception discussed in this thread for tasks with 9-prefixed project IDs. I am able to successfully retrieve all completed tasks for all of my Todoist projects by changing line 1058 of `pytodoist\todoist.py` from:

```python
project = self.owner.projects[task_json['project_id']]
```
to
```python
try:
    project = self.owner.projects[task_json['project_id']]
except KeyError:
    project = self.owner.projects[task_json['project_id'] - 805_306_368]
```

This temporary fix works for me, but I am not sure if this will work for other users. In particular, the magic `805_306_368` number may be specific to my account.

Is there a more elegant way to implement handling for the invalid project ID formats? I am not yet familiar enough with the Todoist API to be confident in creating a pull request-worthy solution.

**Comment by ryqiem** [comment] 2018-06-04 13:08
Great work @pete-adriano-debiase 

I've created a ticket for Todoist support (maybe a bit prematurely), let's see if they can shed any light on this.

**Comment by rohitpaulk** [comment] 2018-06-12 09:48
I was hoping that I'd be able to replicate this against my account, but that didn't work.

@pete-adriano-debiase @ryqiem Could you share one instance of a task + project ID combination that caused the script to fail? Values I'm looking for: 

- The task ID
- The wrong project ID
- The correct project ID (if you know what it is)

Feel free to post these values here, or send to `support@todoist.com` or `rohitpaulk@doist.com`.

In the meantime, I'll pass on the project IDs I see on this thread to the concerned devs to see if they can spot something unusual.

**Comment by pete-adriano-debiase** [comment] 2018-06-12 10:29
Hi @rohitpaulk, thanks so much for looking into this. Here is the requested info for a few completed tasks from my account that might be worth looking at. I picked two tasks on either side of the date of 2018-04-09 on which this issue may have started to occur.

| Task ID    | Project ID in Response | Correct Project ID | Date Completed                 |
|------------|------------------------|--------------------|--------------------------------|
| 2584361591 | 936939558              | 131633190          | Wed 11 Apr 2018 08:49:57 +0000 |
| 2599950584 | 936939558              | 131633190          | Tue 10 Apr 2018 11:23:04 +0000 |
| 2587633490 | 131633190              | 131633190          | Mon 09 Apr 2018 03:33:32 +0000 |
| 2586839303 | 131633190              | 131633190          | Mon 09 Apr 2018 03:14:41 +0000 |

For the first two tasks in this table, the value in the `items` > `project_id` field in the response I'm getting from Todoist seems to be larger than the correct project ID by the magic number of `805_306_368`. This response was obtained via a call to the `get_all_completed_tasks` function of Todoist's Python API.

**Comment by rohitpaulk** [comment] 2018-06-12 10:39
Thanks, @pete-adriano-debiase! I've passed these values on to our team, will share an update soon.

**Comment by imankulov** [comment] 2018-07-04 11:59
Hey guys,

Thanks a lot for the report and for the investigation, especially for @pete-adriano-debiase, who went to great lengths to find out the root cause and the workaround.  It was an API issue indeed, and we've just fixed it and deployed changes to production. It should fix the issue, but please let me know if it still doesn't.

**Comment by pete-adriano-debiase** [comment] 2018-07-09 10:04
Hi @imankulov,

Thanks so much for taking a look at this and posting your update!

Unfortunately, I still seem to be experiencing the same problem. Perhaps we can approach this from another angle. I have the following pure Todoist API code.

```python
from pytodoist.api import TodoistAPI
import json

api = TodoistAPI()
response = api.login('email_address@some_domain.com', 'super_secret_password')
user_info = response.json()
user_token = user_info['token']
response = api.get_all_completed_tasks(user_token)
all_completed_tasks = response.json()
```

Upon running this script, `all_completed_tasks` stores the JSON data attached below (task names changed to "Task" and project names changed to "Project" for privacy).

[todoist_sample_response_JSON.txt](https://github.com/Garee/pytodoist/files/2175569/todoist_sample_response_JSON.txt)

In this JSON response, each completed task in the `items` array has a `project_id` value starting with a `9`. However, in the `projects` array, each project has an `id` value starting with a `1`. None of the `project_id` values match any of the `id` values, and the difference between the 9-prefixed `project_id` values and the respective 1-prefixed `id` values is always `805_306_368` (this can only be verified if you already know which completed tasks correspond to which projects).

Is this the intended behavior? Please don't hesitate to let me know if there's anything I can do to help nail this down.

**Comment by imankulov** [comment] 2018-07-09 12:34
Sorry for the issue @pete-adriano-debiase and thanks for detailed debugging info. WIll have a closer look on it later today or tomorrow.

**Comment by imankulov** [comment] 2018-07-12 15:09
Hi @pete-adriano-debiase. Sorry, I tried hard to reproduce the issue, but no luck at all. I used to be able to reproduce the problem on my account before we applied the fix, but now it returns correct results.

## Some more details.

**If the issue can be reproduced**, then it's only valid for old projects (ones that were created more than about a year ago). Inbox is probably the best candidate for the test. So it makes sense to create and complete a task in the inbox to see if it's still a problem.

**The API URL** has to be `https://api.todoist.com/API/v7/`

```python
>>> api.URL
'https://api.todoist.com/API/v7/'
```

**The output for project ids** has to be coherent and has to contain "small integers" (ones which start with 1, not those which start with 9)

**Finally, to make it a bit less obscure**, `805_306_368` is nothing but `3 << 28`. It's a constant for your account, totally internal, and related to the fact that your account belongs to the database shard number three.

Can you please try to test it one more time to see if it's still a problem.

**Comment by pete-adriano-debiase** [comment] 2018-07-13 01:17
Hi @imankulov, no idea what (if anything) changed between Sunday and today, but I just tested again and am happy to confirm that everything appears to be working normally! Thank you so much for your help and responsiveness.

@ryqiem, can you test to see if things are working on your end and then close this issue if they are?

**Comment by ryqiem** [comment] 2018-07-14 09:42
Unfortunately I get the same error as back in may – looks like our errors might be unrelated :S

```python
Traceback (most recent call last):
  File "script.py", line 13, in <module>
    user = todoist.login('ryqiem@gmail.com', 'supersecretpassword')
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 45, in login
    user = _login(API.login, email, password)
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 102, in _login
    return User(user_json)
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 310, in __init__
    self.sync()
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 350, in sync
    self._sync_tasks(response_json['items'])
  File "/home/martin/.local/lib/python3.5/site-packages/pytodoist/todoist.py", line 371, in _sync_tasks
    project = self.projects[project_id]
KeyError: 182086891
```

**Comment by imankulov** [comment] 2018-07-16 12:05
@ryqiem, I happen to have the same error on my account. Made a PR with explanation and fix (or a workaround) in #27.

**Comment by ryqiem** [comment] 2018-07-16 18:05
@imankulov Great, thanks! 

I'm not very good with pip – I installed pytodoist through it, but how do I integrate your PR?

Sorry about requiring direct help, hope you have time! If not, no worries :-)

**Comment by Garee** [comment] 2018-07-17 19:56
@ryqiem I published new version of the package which includes @imankulov PR changes. Please update the package:

`$ pip install pytodoist`

**Comment by ryqiem** [comment] 2018-07-21 12:10
@Garee @imankulov You guys are the best! It's working well again!

**Closed** 2018-07-21 12:17 UTC
