### ISSUE TITLE
Keep getting keyerror = NUM on user login

### ISSUE THREAD

**Issue by JackPo** [Garee/pytodoist#12] opened 2016-05-23 07:13 UTC
```python
# !/usr/bin/env python

import sys
import time
import subprocess
from pytodoist import todoist
api_token = TOKEN
user = todoist.login_with_api_token(api_token)

projects = user.get_projects()
for project in projects:
        print(project.name)
```

**Comment by Garee** [comment] 2016-05-23 09:56
Which version are you using? I am unable to replicate the issue.

```bash
$ pip freeze | grep pytodoist
pytodoist==2.0.4
```

If you are not using the latest version can you please try upgrading?

```bash
$ pip install pytodoist --upgrade
```

**Comment by JackPo** [comment] 2016-05-24 06:35
am indeed using the latest version.    Full error:

Traceback (most recent call last):
  File "todoist_stats.py", line 7, in <module>
    user = todoist.login_with_api_token(api_token)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytodoist/todoist.py", line 92, in login_with_api_token
    return User(user_json)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytodoist/todoist.py", line 325, in __init__
    self.sync()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytodoist/todoist.py", line 368, in sync
    self._sync_notes(response_json['Notes'])
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pytodoist/todoist.py", line 395, in _sync_notes
    task = self.tasks[task_id]
KeyError: 40204181

**Comment by Garee** [comment] 2016-06-03 10:59
Are you still experiencing this? Unfortunately, I've had no luck replicating the issue. I'm not sure what the problem is.

**Comment by Garee** [comment] 2016-08-20 10:09
I'm closing this as I haven't been able to replicate it and no one else has complained about it. If it happens again please let me know.

**Comment by ariporad** [comment] 2016-09-02 21:53
@Garee: I'm having this too. It's intermittent though. Full stack trace:

```
Traceback (most recent call last):
  File "index.py", line 167, in <module>
    main()
  File "index.py", line 154, in main
    user = todoist.login_with_api_token(TODOIST_API_TOKEN)
  File "/Users/ariporad/dev/schoology-importer/venv/lib/python3.5/site-packages/pytodoist/todoist.py", line 92, in login_with_api_token
    return User(user_json)
  File "/Users/ariporad/dev/schoology-importer/venv/lib/python3.5/site-packages/pytodoist/todoist.py", line 325, in __init__
    self.sync()
  File "/Users/ariporad/dev/schoology-importer/venv/lib/python3.5/site-packages/pytodoist/todoist.py", line 366, in sync
    self._sync_tasks(response_json['Items'])
  File "/Users/ariporad/dev/schoology-importer/venv/lib/python3.5/site-packages/pytodoist/todoist.py", line 387, in _sync_tasks
    project = self.projects[project_id]
KeyError: 179336502
```

Version:
```
$ pip freeze | grep pytodoist
pytodoist==2.0.4
```

Thanks!

**Comment by Garee** [comment] 2016-11-14 19:38
I'm hoping this issue will be fixed when I start using the v7 API. On hold until then.

**Comment by Garee** [comment] 2017-02-25 14:07
I have released a new version that uses v7 of the API. Please upgrade and let me know if you encounter this issue again.

```
$ pip install pytodoist --upgrade
```

I'm going to close this issue for the moment.

**Closed by Garee** 2017-02-25 14:07 UTC
Labels: investigation, on hold
